# Introduction to Data Science and Machine Learning

<p align="center">
    <img width="699" alt="image" src="https://user-images.githubusercontent.com/49638680/159042792-8510fbd1-c4ac-4a48-8320-bc6c1a49cdae.png">
</p>

---

## KNN and Linear regression - Homework

Here a couple of exercises to better fix in your mind the working schemas of KNN and Linear Regression algorithms.

### KNN

#### Exercise 1

> Use $k$NN just implemented to solve a classification problem. (_e.g._ the notorious Iris classification problem).

##### Import data

In [1]:
# I imported data for you. Your are welcome! 🙂
import pandas as pd
import numpy as np

from sklearn.datasets import load_iris

data = load_iris()

X = data['data']
y = data['target']

print(f"Dataset is made by {len(X)} data, whose first 5 lines are \n {X[:5]} \n ")
print(f"Target vector is {len(y)}-long, and targets names are \n {data['target_names']}")

Dataset is made by 150 data, whose first 5 lines are 
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]] 
 
Target vector is 150-long, and targets names are 
 ['setosa' 'versicolor' 'virginica']


#### Exercise 2

> Apply $k$NN to the [wave energy outputs regression problem](https://archive.ics.uci.edu/ml/datasets/Wave+Energy+Converters#) with a big dataset. Use different metrics and compare numerical performances.